apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  consul.server: |
    consul:53 {
        errors
        cache 30
        forward . 10.10.1.6  # this is my test/dev DNS server
    }