apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app":"realtimeapp","app.kubernetes.io/managed-by":"pulumi"},"name":"realtimeapp","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"realtimeapp"}},"template":{"metadata":{"labels":{"app":"realtimeapp"}},"spec":{"containers":[{"env":[{"name":"REDISHOST","value":"redisapp:6379"}],"image":"gbaeke/fluxapp:1.0.0","name":"realtimeapp","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"150m","memory":"150Mi"},"requests":{"cpu":"25m","memory":"50Mi"}}}]}}}}
  creationTimestamp: "2020-05-02T19:41:08Z"
  generation: 1
  labels:
    app: realtimeapp
    app.kubernetes.io/managed-by: pulumi
  name: realtimeapp
  namespace: default
  resourceVersion: "870"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/realtimeapp
  uid: ec93d364-56e3-4ff9-9276-24a767eaf94d
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: realtimeapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: realtimeapp
    spec:
      containers:
      - env:
        - name: REDISHOST
          value: redisapp:6379
        image: gbaeke/realtime-go:consul1
        imagePullPolicy: IfNotPresent
        name: realtimeapp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
          requests:
            cpu: 25m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-05-02T19:41:43Z"
    lastUpdateTime: "2020-05-02T19:41:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-02T19:41:08Z"
    lastUpdateTime: "2020-05-02T19:41:43Z"
    message: ReplicaSet "realtimeapp-66f75f6cfb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
